name: Pulumi

on:
  - pull_request

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - run: pip install -r requirements.txt
        working-directory: ${{ github.workspace }}/infra # Location of Pulumi code

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: youtube-subs/prod
          work-dir: ${{ github.workspace }}/infra # Location of Pulumi code
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
